version: "3.9"

services:
  swoole:
    build: .
    container_name: swoole_app
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
#      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "9501:9501"
    command: ["php", "/var/www/html/src/main.php"]
    restart: "no"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
